### ISSUE TITLE
Question: polling or subscribing

### ISSUE THREAD

**Issue by hklages** [pduck27/hp2mqtt#9]
Hi - just a question. 
Do I understand it right: It works in one direction - from mqtt to hp2. It is not possible to listen to any events/published messages from homepilot?

**Comment by pduck27** [comment]
Hi,

yes, the interface only allows push requests in direction to the homepilot. I plan to do integrate a frequently check of homepilot's device information to gather the current device state when an action was released from homepilot. Put this will not be realtime, maybe each minute.

**Comment by hklages** [comment]
Thanks. I asked Rademacher whether they intend to implement mqtt - but havent received any answer.
